name: Publish documentation
on:
  workflow_dispatch: # On manual trigger
  push:
    branches:
      - main

jobs:
  build:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build static documentation and publish
        run: mkdocs gh-deploy --force
        # https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages
